// Writes icon-packs/default/<slug>.png and .webp for every catalog icon.
// Re-run after adding catalog icons: npm run icons:generate-default
import { mkdirSync, writeFileSync } from 'node:fs';
import sharp from 'sharp';
import { CATALOG_ICONS } from '../src/lib/iconCatalog';
import { iconSvg } from './defaultIconGlyphs';

const OUT = 'icon-packs/default';

async function main() {
  mkdirSync(OUT, { recursive: true });
  for (const icon of CATALOG_ICONS) {
    const svg = Buffer.from(iconSvg(icon));
    await sharp(svg).png().toFile(`${OUT}/${icon.slug}.png`);
    await sharp(svg).webp({ quality: 90 }).toFile(`${OUT}/${icon.slug}.webp`);
  }
  writeFileSync(
    `${OUT}/LICENSE.md`,
    'Generated by scripts/generateDefaultIcons.ts. Glyphs: Lucide (ISC, https://lucide.dev/license) and Simple Icons (CC0, https://simpleicons.org). Brand logos remain trademarks of their owners.\n',
  );
  console.log(`Wrote ${CATALOG_ICONS.length * 2} icons to ${OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
