// The look of each generated icon pack: a 256px SVG per catalog icon, built from the same openly licensed glyphs
// as the default pack (Lucide, ISC; Simple Icons, CC0). Add a pack: a style here + an entry in ICON_PACKS
// (src/lib/iconCatalog.ts), then `npm run icons:generate -- <id>`.
import type { CatalogIcon } from '../src/lib/iconCatalog';
import { GRADIENTS, glyphMarkup, iconSvg } from './defaultIconGlyphs';

const TILE = 'x="8" y="8" width="240" height="240" rx="56"';

function rgb(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

/** `hex` moved `amount` (0-1) of the way towards `base`. */
export function mix(hex: string, base: string, amount: number): string {
  const a = rgb(hex);
  const b = rgb(base);
  return `#${a.map((v, i) => Math.round(v + (b[i] - v) * amount).toString(16).padStart(2, '0')).join('')}`;
}

function svg(body: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256">\n${body}\n</svg>`;
}

/** Frosted glass: a see-through tint of the category colour, a bright rim and sheen, a white glyph with a soft shadow. */
function glass(icon: CatalogIcon): string {
  const [top, bottom] = GRADIENTS[icon.category];
  return svg(`<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${top}" stop-opacity=".55"/><stop offset="1" stop-color="${bottom}" stop-opacity=".85"/></linearGradient>
<linearGradient id="s" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff" stop-opacity=".55"/><stop offset=".45" stop-color="#fff" stop-opacity=".08"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient></defs>
<rect ${TILE} fill="#ffffff" fill-opacity=".35"/>
<rect ${TILE} fill="url(#g)"/>
<rect ${TILE} fill="url(#s)"/>
<rect x="9.5" y="9.5" width="237" height="237" rx="54.5" fill="none" stroke="#ffffff" stroke-opacity=".6" stroke-width="3"/>
<g transform="translate(0 4)" opacity=".22">${glyphMarkup(icon, '#000000')}</g>
${glyphMarkup(icon, '#ffffff')}`);
}

/** Outline: an off-white tile with a ring and glyph in the category colour. */
function outline(icon: CatalogIcon): string {
  const [, bottom] = GRADIENTS[icon.category];
  return svg(`<rect ${TILE} fill="#fbfaf7"/>
<rect x="14" y="14" width="228" height="228" rx="50" fill="none" stroke="${bottom}" stroke-width="10"/>
${glyphMarkup(icon, bottom)}`);
}

/** Pastel: a soft tint of the category colour with a deeper glyph. */
function pastel(icon: CatalogIcon): string {
  const [top, bottom] = GRADIENTS[icon.category];
  return svg(`<rect ${TILE} fill="${mix(top, '#ffffff', 0.6)}"/>
${glyphMarkup(icon, mix(bottom, '#000000', 0.2))}`);
}

/** Mono light: a pale grey tile, a near-black glyph. */
function monoLight(icon: CatalogIcon): string {
  return svg(`<rect ${TILE} fill="#f2f2f0"/>
<rect x="8.75" y="8.75" width="238.5" height="238.5" rx="55.25" fill="none" stroke="#000000" stroke-opacity=".08" stroke-width="1.5"/>
${glyphMarkup(icon, '#1d1c1a')}`);
}

/** Mono dark: a near-black tile, a warm white glyph. */
function monoDark(icon: CatalogIcon): string {
  return svg(`<rect ${TILE} fill="#1d1c1a"/>
<rect x="8.75" y="8.75" width="238.5" height="238.5" rx="55.25" fill="none" stroke="#ffffff" stroke-opacity=".1" stroke-width="1.5"/>
${glyphMarkup(icon, '#f2efe9')}`);
}

export const PACK_STYLES: Record<string, (icon: CatalogIcon) => string> = {
  default: iconSvg,
  glass,
  outline,
  pastel,
  'mono-light': monoLight,
  'mono-dark': monoDark,
};

export const GENERATED_PACKS = Object.keys(PACK_STYLES);

export function packLicense(pack: string): string {
  return `Generated by scripts/generateIconPacks.ts (the "${pack}" style in scripts/iconPackStyles.ts). Glyphs: Lucide (ISC, https://lucide.dev/license) and Simple Icons (CC0, https://simpleicons.org). Brand logos remain trademarks of their owners.\n`;
}
